### ISSUE TITLE
The behavior of TRandom.Next(int, int) is different from the built-in's.

### ISSUE THREAD

**Issue by Zhouxing-Su** [pomma89/Troschuetz.Random#4]
As https://msdn.microsoft.com/en-us/library/2dx6wyd4(v=vs.110).aspx mentioned:

> ### Remarks
> The Next(Int32, Int32) overload returns random integers that range from minValue to maxValue – 1. However, if maxValue equals minValue, the method returns minValue.

It should not raise an exception when (minValue == maxValue).

**Comment by pomma89** [comment]
Nice catch, thank you. Fixed and published on NuGet.
